apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
       - name: nodeapp-backend
         image: public.ecr.aws/s3k1y8m9/test-ecr-repo:latest
         ports:
         - name: http
           containerPort: 8080
         resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m