apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8082
      targetPort: 8080
